[package]
name = "advent2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Buckled for the iterator tools
[dependencies]
itertools = "0.10.5"
regex = "1.7.0"
trees = "0.4.1"
